"""Load and query the parameter schema (generated by gui/tools/gen_schema.py from bin/NGenomeSyn)."""
import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent
SCHEMA_PATH = _HERE.parent / "resources" / "params_schema.json"


class Schema:
    _data = None

    @classmethod
    def data(cls):
        if cls._data is None:
            cls._data = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        return cls._data

    @classmethod
    def params(cls):
        return cls.data()["params"]

    @classmethod
    def param(cls, name):
        for p in cls.params():
            if p["name"] == name:
                return p
        return None

    @classmethod
    def by_category(cls, scope):
        """Ordered {category: [param, ...]} for a scope ('global' or 'track')."""
        order = list(cls.data()["categories"].keys())
        out = {c: [] for c in order}
        for p in cls.params():
            if scope in p["scope"]:
                out.setdefault(p["category"], []).append(p)
        return {c: v for c, v in out.items() if v}

    @classmethod
    def categories(cls):
        return cls.data()["categories"]

    @classmethod
    def plot_types(cls):
        return cls.data().get("plot_types", [])

    @classmethod
    def aliases(cls):
        return cls.data()["aliases"]

    @classmethod
    def resolve_alias(cls, name):
        """Map legacy/doc param names to the engine key, following the chain."""
        seen = set()
        while name in cls.aliases() and name not in seen:
            seen.add(name)
            name = cls.aliases()[name]
        return name

    @classmethod
    def resolve_plot_type(cls, value):
        """Map a legacy plot_type spelling ("lines", "histogram", ...) to the
        canonical name carried by the combo (unknown/empty pass through)."""
        if not value:
            return value
        for pt in cls.plot_types():
            if value in pt.get("aliases", ()):
                return pt["name"]
        return value

    @classmethod
    def palettes(cls):
        return cls.data().get("palettes") or {"builtin": {}, "files": {}}

    @classmethod
    def palette_colors(cls, name):
        """Hex colors of a palette (builtin first, then ColorsBrewer files)."""
        name = (name or "").strip()
        if not name:
            return None
        pals = cls.palettes()
        for grp in ("builtin", "files"):
            entry = pals.get(grp, {}).get(name)
            if entry and entry.get("colors"):
                return entry["colors"]
        return None
